name: Deploy to HuggingFace Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 履歴を全て取得（shallowクローンを防ぐ）
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to HuggingFace Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"
          # LFSを無効化してpush
          git config --global lfs.https://huggingface.co/.skipdownload true
          git push --force https://user:${HF_TOKEN}@huggingface.co/spaces/yusei68/AI-note main